### ISSUE TITLE
Feature Request- //expand - ability to expand a region from bedrock to build limit.

### ISSUE THREAD

**Issue by ProsperCraft** [JimiIT92/UniverseGuard#13]
With worldguard we would select two corners of a spawn area then //expand vert to set it from bedrock to build limit.  Would love this feature here.

also //expand north 10  for example worked.

**Comment by JimiIT92** [comment]
That feature is in working and will be in the next version. The problem is that i'm really really super busy with my work right now and so i don't have that much time to work on UG :/ Also i'm looking how to improve regions and flags management in code, since i don't really like how it is right now. But yeah, this feature will finally be added ;)
