### ISSUE TITLE
Armor Stand (Holograms) Needs Own Flag

### ISSUE THREAD

**Issue by SerendipityMC** [JimiIT92/UniverseGuard#4]
As title suggests. Armor stands, often used for floating text by servers, are currently under the "mobs" flag, and needs to either be excluded or listed under its own flag.

**Comment by JimiIT92** [comment]
If you say they are under the mobs flag than this is a bug, because they're behavior should not be determined by that flag, but by the "build" flag. But if you prefer i can still add a specific flag (armorstands i guess?). In any case will look into this problem to not refer the armor stands to the mobs flag ;)
