### ISSUE TITLE
build = false

### ISSUE THREAD

**Issue by bombaroberta** [JimiIT92/UniverseGuard#8]
hi all.
I have set false on build flags in my world but players can destroy and can't build it's normal ?

**Comment by JimiIT92** [comment]
Check if players are in a region with that flag set to true or if they are in the global region and the global flag is set to true. Also make sure you have the latest version (1.0.5) wich can be found on Sponge Ore's page or here [https://mega.nz/#!9JN2xZpb!iiE2rSWTss0yoB7hLEbZ4xFUirEfI_q_wkOvyVarFgY](https://mega.nz/#!9JN2xZpb!iiE2rSWTss0yoB7hLEbZ4xFUirEfI_q_wkOvyVarFgY)

**Comment by bombaroberta** [comment]
I use this version.
I have set false on build in the world.json and universguard.conf and i don't know how i can see if global flag is set to true

**Comment by JimiIT92** [comment]
to view it in game you can use the command /region globallist. To know if you are in a region use the /region info command. If it tells that you are not in a region and, using /region globallist, it tells you the build flag is false than there must be something wrong, because in all my previous tests that flag always worked. I can suggest it could be a permission problem at this point (maybe for some reason your players has enough permissions to bypass region flags)

**Comment by bombaroberta** [comment]
ok now it's work i just reinstate universguard but now i have an other problem i use nation and when player has a claim they can"t build.
Do you know something about this because it's really annoying.
